Numerical Python - numpy(for speed)
numpy forces all data to be of same type and stores them continuously
Pandas - loads and cleans the dataset and converts it back into Numpy arrays

In [3]:
import sys
print(sys.executable)

c:\Users\jaisw\DSA\.venv\Scripts\python.exe


In [4]:
!pip install numpy


   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.8 MB 3.4 MB/s eta 0:00:04
   ---- ----------------------------------- 1.6/12.8 MB 3.9 MB/s eta 0:00:03
   ------- -------------------------------- 2.4/12.8 MB 3.9 MB/s eta 0:00:03
   --------- ------------------------------ 2.9/12.8 MB 3.8 MB/s eta 0:00:03
   ----------- ---------------------------- 3.7/12.8 MB 3.7 MB/s eta 0:00:03
   ------------- -------------------------- 4.5/12.8 MB 3.7 MB/s eta 0:00:03
   ---------------- ----------------------- 5.2/12.8 MB 3.7 MB/s eta 0:00:03
   ------------------ --------------------- 6.0/12.8 MB 3.7 MB/s eta 0:00:02
   -------------------- ------------------- 6.6/12.8 MB 3.6 MB/s eta 0:00:02
   ---------------------- ----------------- 7.3/12.8 MB 3.5 MB/s eta 0:00:02
   ------------------------ --------------- 7.9/12.8 MB 3.5 MB/s eta 0:00:02
   --------------------------- ------------ 8.7/12.8 MB 3.5 MB/s eta 0:00:02
   ---

In [5]:
import numpy as np 

my_list = [10,20,30]
arr = np.array(my_list)

print(arr)
print(type(arr))

[10 20 30]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np

arr = np.array([[2,5,9],[1,4,6]])
print(arr)

print(np.ones((2,5)))
print(np.zeros((3,3)))

[[2 5 9]
 [1 4 6]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


np.random.rand() has a range of [0,1) , it generates an array of any shape we specify , rand has arguments for matrix shape example : rand_num = np.random.rand(2,5) , generates a np array of 2x5.

np.random.randint() has [inclusive, exclusive) range, returns a single integer , unless we specify a size.
rand_array = np.random.randint(2, 5, size=(2, 5))
[[4 3 2 2 4]
[2 3 3 4 2]]

In [41]:
import numpy as np

seq = np.arange(0,10,3)
print(seq)
rand_num = np.random.rand(2,4)
print(rand_num)
rand_arr = np.random.randint(3,76,size=(3,3))
print(rand_arr)

[0 3 6 9]
[[0.65788504 0.11422242 0.18450098 0.59229991]
 [0.04269645 0.50293623 0.85022039 0.77280724]]
[[63 11 30]
 [58 47 38]
 [58 18 71]]


In [45]:
import numpy as np

price = np.random.randint(2,92,size=(4,6))
print(price)
new_price = price * 100
print(new_price)

[[43 39 19 40 70 80]
 [30 81 82 53 70 31]
 [91 53 11 44 20 45]
 [31 78 25 30 13 70]]
[[4300 3900 1900 4000 7000 8000]
 [3000 8100 8200 5300 7000 3100]
 [9100 5300 1100 4400 2000 4500]
 [3100 7800 2500 3000 1300 7000]]


Slicing and Indexing
slicing: arr_name[row_start:row_end, col_start:col_end]

In [64]:
import numpy as np

arr=np.random.randint(1,64,size=(1,8))
print(arr)
print(arr[:,2:6])
matrix = np.random.randint(4,98,size=(3,3))
print(matrix)
print(matrix[0:2,0:3])

[[35 41 60 61 13  7  7 43]]
[[60 61 13  7]]
[[79 85 43]
 [64 29 24]
 [90 48 88]]
[[79 85 43]
 [64 29 24]]


In [ ]:
scores = np.random.randint(55,62,size=(1,5))
print(scores)

mask = scores>57
print(mask)
print(scores[mask])

[[61 58 59 61 57]]
[[ True  True  True  True False]]
[61 58 59 61]


In [128]:
study_hours = np.array([2,3,5,1,9,7])

real_study_hours = study_hours + 1
print(real_study_hours)
True_hours = real_study_hours > 5
print(real_study_hours[True_hours])

old_study_hours = study_hours.reshape(3,2)
print(old_study_hours)
print(old_study_hours.ndim)

[ 3  4  6  2 10  8]
[ 6 10  8]
[[2 3]
 [5 1]
 [9 7]]
2


In [102]:
import numpy as np
print(np.__version__)

2.3.5


Axis concept: 
axis = 0, Vertical
axis = 1, Horizontal

In [89]:
matrix = np.array([
    [10, 20],  
    [30, 40]  
])

print(matrix.sum(axis=0)) 
print(matrix.sum(axis=1))

[40 60]
[30 70]


np.mean(): Average.

np.std(): Standard Deviation (How "spread out" the data is).

np.min() / np.max(): Lowest and Highest values.

np.argmax() / np.argmin(): Crucial. Returns the Index of the max/min value, not the value itself. (Used to find which class the model predicted with highest probability).

In [91]:
scores = np.array([10, 50, 90, 20])

print(np.mean(scores))  
print(np.max(scores))    
print(np.argmax(scores)) 

42.5
90
2


In [93]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
vector = np.array([1, 0, 1])

result = matrix + vector 
# It effectively does:
# [1, 2, 3] + [1, 0, 1] = [2, 2, 4]
# [4, 5, 6] + [1, 0, 1] = [5, 5, 7]
print(result)

[[2 2 4]
 [5 5 7]]


In [99]:
marks = np.array([
    [50, 60, 70, 80], 
    [90, 95, 90, 95], 
    [30, 30, 30, 30]  
])
avg_subject = np.mean(marks,axis=0)
print(f"Subject Averages: {avg_subject}")

total_score = marks.sum(axis=1)
print(f"Total Scores: {total_score}")

top_index = np.argmax(total_score)
print(f"Index of Topper : {top_index}")

Subject Averages: [56.66666667 61.66666667 63.33333333 68.33333333]
Total Scores: [260 370 120]
Index of Topper : 1


use @ for matrix multiplication

In [127]:
import numpy as np

np.random.seed(42)

input = np.random.rand(3,4)
print("Inputs: \n",matrix)

weights = np.random.rand(4,1)
print("Weights :\n",weights)

Bias = np.random.randn()
print("Bias :\n",Bias)

Z = input @ weights + Bias
print("\n Linear step output (Z):\n",Z)

output = np.maximum(Z,0)
print("\n Final Ativated Output: \n",output)


Inputs: 
 [[0.37454012 0.95071431 0.73199394 0.59865848]
 [0.15601864 0.15599452 0.05808361 0.86617615]
 [0.60111501 0.70807258 0.02058449 0.96990985]]
Weights :
 [[0.83244264]
 [0.21233911]
 [0.18182497]
 [0.18340451]]
Bias :
 0.24196227156603412

 Linear step output (Z):
 [[0.99851071]
 [0.57438424]
 [1.07433616]]

 Final Ativated Output: 
 [[0.99851071]
 [0.57438424]
 [1.07433616]]


In [123]:
x=np.random.randn(3,4)
print(x)

[[-1.91328024 -1.72491783 -0.56228753 -1.01283112]
 [ 0.31424733 -0.90802408 -1.4123037   1.46564877]
 [-0.2257763   0.0675282  -1.42474819 -0.54438272]]


In [125]:
probs = np.array([0.1, 0.7, 0.4, 0.9])
preds = np.where(probs > 0.5, 1, 0) 
print(preds)

[0 1 0 1]


Pandas - Excel of Python
(Handles the messy data)

In [5]:

import pandas as pd

df = pd.DataFrame({"A": [1, 2], "B": [3, 4]})
print(df)


ModuleNotFoundError: No module named 'pandas'

In [2]:
%pip install pandas


  Using cached pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   -- ------------------------------------- 0.8/11.0 MB 3.5 MB/s eta 0:00:03
   --- ------------------------------------ 1.0/11.0 MB 2.1 MB/s eta 0:00:05
   ---- ----------------------------------- 1.3/11.0 MB 2.3 MB/s eta 0:00:05
   ----- ---------------------------------- 1.6/11.0 MB 1.9 MB/s eta 0:00:06
   ------- -------------------------------- 2.1/11.0 MB 1.9 MB/s eta 0:00:05
   -------- ------------------------------- 2.4/11.0 MB 1.8 MB/s eta 0:00:05
   ----------- ---------------------------- 3.1/11.0 MB 2.1 MB/s eta 0:00:04
   ------------ --------------------------- 3.4/11.0 MB 2.0 MB/s eta 0:00:04
   ------------- -------------------------- 3.7/11.0 MB 1.9 MB/s eta 0:00:04
   ---------------- ------------

In [1]:
import pandas as pd

df = pd.DataFrame({"A": [1, 2], "B": [3, 4]})
print(df)


   A  B
0  1  3
1  2  4
